version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8.10
    steps:
      - run:
          name: List files
          command: ls -la
      - run:
          name: Detect changes
          command: |
            API_CHANGED=`git diff HEAD^ HEAD packages/api | grep -m 1 "packages/api"`
            if [ $API_CHANGED != "" ]
            then
              touch build-api.job
            fi

            CMS_CHANGED=`git diff HEAD^ HEAD packages/cms | grep -m 1 "packages/cms"`
            if [ $CMS_CHANGED != "" ]
            then
              touch build-cms.job
            fi
      - run:
          name: Install
          command: |
            BUILD_API=`ls | grep "build-api.job"`
            if [ $BUILD_API != "" ]
            then
              lerna boostrap --scope api
            fi

            BUILD_CMS=`ls | grep "build-cms.job"`
            if [ $BUILD_CMS != "" ]
            then
              lerna boostrap --scope cms
            fi
      - run:
          name: Test
          command: |
            BUILD_API=`ls | grep "build-api.job"`
            if [ $BUILD_API != "" ]
            then
              cd packages/api && npm test
            fi

            BUILD_API=`ls | grep "build-cms.job"`
            if [ $BUILD_CMS != "" ]
            then
              cd packages/cms && npm test
            fi
      - run:
          name: Deploy
          command: |
            BUILD_API=`ls | grep "build-api.job"`
            if [ $BUILD_API != "" ]
            then
              cd packages/api && echo "Deploy new build of RESTful API server"
            fi

            BUILD_API=`ls | grep "build-cms.job"`
            if [ $BUILD_CMS != "" ]
            then
              cd packages/cms && echo "Deploy new build of CMS server"
            fi
      - run:
          name: Clean up
          command: rm -f build-*

