version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8.10
    working_directory: ~/mono-repo
    steps:
      - checkout
      - run:
          name: List files
          command: ls -la ~/mono-repo
      - run:
          name: Install lerna
          command: sudo npm install -g lerna
      - run:
          name: Detect changes
          command: |
            API_CHANGED=`git diff HEAD^ HEAD packages/api | grep -m 1 "packages/api"`
            if [ "${API_CHANGED}" != "" ]
            then
              touch build-api.job
            fi

            CMS_CHANGED=`git diff HEAD^ HEAD packages/cms | grep -m 1 "packages/cms"`
            if [ "${CMS_CHANGED}" != "" ]
            then
              touch build-cms.job
            fi
      - run:
          name: Test
          command: |
            if [ -e build-api.job ]
            then
              echo "Testing api repo..."
              cd packages/api && npm test
            fi

            if [ -e build-cms.job ]
            then
              echo "Testing cms repo..."
              cd packages/cms && npm test
            fi
      - run:
          name: Deploy
          command: |
            if [ -e build-api.job ]
            then
              cd packages/api && echo "Deploy new build of RESTful API server"
            fi

            if [ -e build-cms.job ]
            then
              cd packages/cms && echo "Deploy new build of CMS server"
            fi
      - run:
          name: Clean up
          command: rm -f build-*

