version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8.10
    working_directory: ~/mono-repo
    steps:
      - checkout
      - run:
          name: List files
          command: ls -la ~/mono-repo
      - run:
          name: Install lerna
          command: sudo npm install -g lerna
      - run:
          name: Detect changes in api repo
          command: |
            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
            echo "Commit range:" $COMMIT_RANGE
            echo `git diff $COMMIT_RANGE --name-status packages/api`
            API_CHANGED=$(git diff $COMMIT_RANGE --name-status packages/api | grep -m 1 "packages/api")
            if [ "${API_CHANGED}" != "" ]
            then
              echo "API repo was changed. Setting up build..."
              touch build-api.job
            fi
      - run:
          name: Detect changes in cms repo
          command: |
            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')
            echo "Commit range:" $COMMIT_RANGE
            echo `git diff $COMMIT_RANGE --name-status packages/cms`
            CMS_CHANGED=$(git diff $COMMIT_RANGE --name-status packages/cms | grep -m 1 "packages/cms")
            if [ "${CMS_CHANGED}" != "" ]
            then
              echo "CMS repo was changed. Setting up build..."
              touch build-cms.job
            fi
      - run:
          name: Test for api repo
          command: |
            if [ -e build-api.job ]
            then
              echo "Testing api repo..."
              cd packages/api && npm test
            fi
      - run:
          name: Test for cms repo
          command: |
            if [ -e build-cms.job ]
            then
              echo "Testing cms repo..."
              cd packages/cms && npm test
            fi
      - run:
          name: Deploy api repo
          command: |
            if [ -e build-api.job ]
            then
              cd packages/cms && echo "Deploy new build of API server"
            fi
      - run:
          name: Deploy cms repo
          command: |
            if [ -e build-cms.job ]
            then
              cd packages/cms && echo "Deploy new build of CMS server"
            fi
      - run:
          name: Clean up
          command: rm -f build-*

